#!/usr/bin/env python3
"""Generate packages/schema/src/binds.data.ts from engine-sim generate_setups.py."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "packages/engine-sim/src/engine_sim/generate_setups.py"
OUTPUT = ROOT / "packages/schema/src/binds.data.ts"

PLUS_RE = re.compile(r'''print\('alias \+(walk|strike) "(.*)";'\)''')
MINUS_RE = re.compile(r'''print\('alias -(walk|strike) "(.*)";'\)''')


def extract_match_block(text: str, name: str) -> str:
    match = re.search(rf"match {name}:(.*?)(?=\n    if starting_|\n    match )", text, re.DOTALL)
    if not match:
        raise SystemExit(f"Could not find match block for {name}")
    return match.group(1)


def parse_bind_cases(block: str) -> list[tuple[int, str, str]]:
    cases: list[tuple[int, str, str]] = []
    for case in re.finditer(r"case (\d+):(.*?)(?=case \d+:|$)", block, re.DOTALL):
        index = int(case.group(1))
        body = case.group(2)
        plus = PLUS_RE.search(body)
        minus = MINUS_RE.search(body)
        if not plus or not minus:
            raise SystemExit(f"Missing alias prints for movement/action case {index}")
        cases.append((index, plus.group(2), minus.group(2)))
    return sorted(cases, key=lambda item: item[0])


def ts_single_quoted(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def render_bind_array(name: str, alias: str, cases: list[tuple[int, str, str]]) -> str:
    lines = [f"export const {name}: BindPair[] = ["]
    for _index, plus_body, minus_body in cases:
        plus = ts_single_quoted(f'alias +{alias} "{plus_body}";')
        minus = ts_single_quoted(f'alias -{alias} "{minus_body}";')
        lines.append(f"  {{ plus: {plus}, minus: {minus} }},")
    lines.append("];")
    return "\n".join(lines)


def extract_original_excluded(text: str) -> list[int]:
    match = re.search(r"bad = \[([^\]]+)\]", text)
    if not match:
        return []
    return [int(part.strip()) for part in match.group(1).split(",") if part.strip()]


def main() -> None:
    text = SOURCE.read_text(encoding="utf-8")
    walk_cases = parse_bind_cases(extract_match_block(text, "starting_walk"))
    shot_cases = parse_bind_cases(extract_match_block(text, "starting_shot"))
    excluded = extract_original_excluded(text)

    if len(walk_cases) != 27:
        raise SystemExit(f"Expected 27 movement patterns, found {len(walk_cases)}")
    if len(shot_cases) != 10:
        raise SystemExit(f"Expected 10 action patterns, found {len(shot_cases)}")

    output = f"""// Code generated by scripts/codegen-binds.py — DO NOT EDIT.
import type {{ BindPair }} from "./binds.js";

{render_bind_array("MOVEMENT_BINDS", "walk", walk_cases)}

{render_bind_array("ACTION_BINDS", "strike", shot_cases)}

export const ORIGINAL_EXCLUDED_MOVEMENT = new Set<number>([{", ".join(str(v) for v in excluded)}]);
"""

    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(walk_cases)} movement, {len(shot_cases)} action patterns)")


if __name__ == "__main__":
    main()
